# ===========================
# DEV PROFILE
# Override via: --spring.profiles.active=dev
# ===========================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.advocate.com.advocate_app=DEBUG
logging.level.org.hibernate.SQL=DEBUG
