package advocate.com.advocate_app.service;

import advocate.com.advocate_app.entity.*;
import advocate.com.advocate_app.repository.*;
import advocate.com.advocate_app.storage.DocumentStorageService;
import advocate.com.advocate_app.storage.StoredFile;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class DemoWorkspaceService {

    private static final Logger log = LoggerFactory.getLogger(DemoWorkspaceService.class);

    @Autowired private DemoWorkspaceRepository demoWorkspaceRepository;
    @Autowired private AdvocateRepository advocateRepository;
    @Autowired private ClientRepository clientRepository;
    @Autowired private CaseRepository caseRepository;
    @Autowired private CaseEventRepository caseEventRepository;
    @Autowired private ExpenseRepository expenseRepository;
    @Autowired private InvoiceRepository invoiceRepository;
    @Autowired private ClientPaymentRepository clientPaymentRepository;
    @Autowired private DocumentRepository documentRepository;
    @Autowired private NotificationRepository notificationRepository;
    @Autowired private DocumentStorageService documentStorageService;
    @Autowired private CaseTimelineService timelineService;
    @Autowired private AuditLogService auditLogService;
    @Autowired private NotificationService notificationService;
    @Autowired private CaseFinancialService caseFinancialService;
    @Autowired private CaseTimelineRepository caseTimelineRepository;

    private static final String DEMO_VERSION = "1.0.0";
    private static final Random RANDOM = new Random(42);

    // ── Indian names ──
    private static final String[] FIRST_NAMES = {
        "Aarav", "Vihaan", "Vivaan", "Ananya", "Diya", "Advik", "Kabir", "Arjun",
        "Sara", "Aadhya", "Ranveer", "Pari", "Ishaan", "Myra", "Shaurya", "Aaradhya",
        "Dhruv", "Anaya", "Krishna", "Ayaan", "Ira", "Rudra", "Saanvi", "Shaan",
        "Aishwarya", "Vedant", "Tanvi", "Yash", "Kavya", "Reyansh", "Gauri", "Laksh"
    };

    private static final String[] LAST_NAMES = {
        "Sharma", "Verma", "Patel", "Singh", "Gupta", "Reddy", "Iyer", "Nair",
        "Joshi", "Kulkarni", "Deshmukh", "Menon", "Shah", "Mehta", "Bhatt",
        "Pillai", "Rao", "Chopra", "Malhotra", "Saxena", "Mishra", "Pandey",
        "Srivastava", "Agarwal", "Khanna", "Kapoor", "Thakur", "Rawat", "Das", "Sen"
    };

    private static final String[] CITIES = {
        "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai",
        "Kolkata", "Pune", "Jaipur", "Lucknow", "Surat", "Indore", "Bhopal",
        "Chandigarh", "Nagpur", "Thane", "Visakhapatnam", "Patna", "Vadodara", "Mysuru"
    };

    private static final String[] CASE_TYPES = {
        "Property Dispute", "Cheque Bounce", "Civil Suit", "Family Settlement",
        "Consumer Complaint", "Motor Accident Claim", "Labour Dispute", "Criminal Bail",
        "Divorce Petition", "Contract Dispute", "Recovery Suit", "Partition Suit",
        "Service Matter", "Tax Appeal", "Rent Control", "Matrimonial Dispute"
    };

    private static final String[] STATUSES = {"Active", "Pending", "Closed", "Dismissed"};
    private static final String[] COURT_LEVELS = {"District", "High Court", "Supreme Court"};
    private static final String[] EXPENSE_CATEGORIES = {
        "Travel", "Court Fees", "Documents", "Stationery", "Miscellaneous"
    };
    private static final String[] PAYMENT_MODES = {"Cash", "UPI", "Bank Transfer", "Cheque"};
    private static final String[] HEARING_TYPES = {
        "Hearing", "Preliminary Hearing", "Final Arguments", "Cross Examination",
        "Evidence Recording", "Bail Application", "Case Management"
    };
    private static final String[] DOC_CATEGORIES = {
        "Petition", "Evidence", "Court Order", "Agreement", "Affidavit", "Notice",
        "Judgment", "Invoice", "Payment Receipt", "Other"
    };
    private static final String[] INVOICE_STATUSES = {"PAID", "UNPAID", "OVERDUE"};

    private static final byte[] SAMPLE_PDF_BYTES = createSamplePdf();
    private static final byte[] SAMPLE_TXT_BYTES = "Sample document content for demo workspace.\nThis is a demo file generated by Advocate Management System.\n".getBytes();

    // ── Status DTO ──
    public static class DemoStatus {
        public boolean workspaceEmpty;
        public boolean hasDemoWorkspace;
        public String generatedAt;
        public Map<String, Integer> recordCounts = new LinkedHashMap<>();
    }

    // ── Check status ──
    public DemoStatus getStatus(String email) {
        Advocate advocate = getAdvocate(email);
        DemoStatus status = new DemoStatus();

        long clientCount = clientRepository.countByAdvocateAndDeletedFalse(advocate);
        long caseCount = caseRepository.countByAdvocateAndDeletedFalse(advocate);
        status.workspaceEmpty = (clientCount == 0 && caseCount == 0);

        Optional<DemoWorkspace> existing = demoWorkspaceRepository.findByAdvocateId(advocate.getId());
        status.hasDemoWorkspace = existing.isPresent();
        status.generatedAt = existing.map(dw -> dw.getGeneratedAt().toString()).orElse(null);

        Map<String, Integer> counts = new LinkedHashMap<>();
        counts.put("clients", (int) clientCount);
        counts.put("cases", (int) caseCount);
        counts.put("documents", (int) documentRepository.countByAdvocate(advocate));
        counts.put("hearings", (int) caseEventRepository.countByAdvocate(advocate));
        counts.put("expenses", (int) expenseRepository.countByAdvocate(advocate));
        counts.put("payments", (int) clientPaymentRepository.countByAdvocate(advocate));
        counts.put("invoices", (int) invoiceRepository.countByAdvocate(advocate));
        status.recordCounts = counts;
        return status;
    }

    // ── Generate Demo Workspace ──
    @Transactional
    public Map<String, Object> generate(String email) {
        Advocate advocate = getAdvocate(email);

        if (demoWorkspaceRepository.existsByAdvocateId(advocate.getId())) {
            throw new RuntimeException("Demo workspace already exists for this advocate.");
        }

        log.info("Generating demo workspace for advocate: {} ({})", advocate.getFullName(), advocate.getEmail());

        List<Long> clientIds = new ArrayList<>();
        List<Long> caseIds = new ArrayList<>();
        List<Long> hearingIds = new ArrayList<>();
        List<Long> documentIds = new ArrayList<>();
        List<Long> expenseIds = new ArrayList<>();
        List<Long> invoiceIds = new ArrayList<>();
        List<Long> paymentIds = new ArrayList<>();

        // ── 1. Generate Clients (10–15) ──
        int clientCount = 10 + RANDOM.nextInt(6);
        List<Client> clients = new ArrayList<>();
        for (int i = 0; i < clientCount; i++) {
            Client c = new Client();
            c.setName(randomName());
            c.setEmail(randomEmail(c.getName()));
            c.setPhone("+91-9" + (8000000000L + RANDOM.nextInt(1999999999)));
            c.setAddress(randomCity() + ", India");
            c.setAdvocate(advocate);
            c.setDeleted(i >= clientCount - 2); // last 2 archived
            c.setCreatedAt(LocalDate.now().minusDays(RANDOM.nextInt(180)));
            Client saved = clientRepository.save(c);
            clientIds.add(saved.getId());
            clients.add(saved);
        }
        log.info("Generated {} clients", clientIds.size());

        // ── 2. Generate Cases (20–25) ──
        int caseCount = 20 + RANDOM.nextInt(6);
        List<CaseEntity> cases = new ArrayList<>();
        for (int i = 0; i < caseCount; i++) {
            CaseEntity ce = new CaseEntity();
            ce.setCaseNumber("DEMO/" + (10000 + i) + "/" + (2024 + RANDOM.nextInt(3)));
            ce.setCaseTitle(randomCaseType() + " - " + randomName());
            ce.setCaseType(randomCaseType());
            ce.setCourtLevel(COURT_LEVELS[RANDOM.nextInt(COURT_LEVELS.length)]);
            ce.setStatus(STATUSES[RANDOM.nextInt(STATUSES.length)]);
            ce.setAmount(5000.0 + RANDOM.nextDouble() * 495000.0);
            ce.setDescription("Demo case for " + clients.get(i % clients.size()).getName());
            ce.setAdvocate(advocate);
            ce.setClient(clients.get(i % clients.size()));
            ce.setDeleted(false);
            ce.setCreatedAt(LocalDate.now().minusDays(RANDOM.nextInt(180)));
            ce.setTotalClientAgreedAmount(ce.getAmount());
            ce.setTotalPaidByClient(0.0);
            ce.setTotalExpensesSoFar(0.0);
            ce.setBalanceInAccount(0.0);
            ce.setPendingFromClient(ce.getAmount());
            CaseEntity saved = caseRepository.save(ce);
            caseIds.add(saved.getId());
            cases.add(saved);

            // Timeline: Case Created
            try {
                timelineService.recordEvent(
                        saved.getId(), saved.getClient() != null ? saved.getClient().getId() : null,
                        advocate.getId(), CaseTimelineService.CASE_CREATED,
                        "Case Created", "Demo case " + saved.getCaseNumber() + " created",
                        "System (Demo)", "Case", saved.getId()
                );
            } catch (Exception e) {
                log.warn("Timeline record failed: {}", e.getMessage());
            }
        }
        log.info("Generated {} cases", caseIds.size());

        // ── 3. Generate Hearings (15) ──
        LocalDate today = LocalDate.now();
        for (int i = 0; i < 15; i++) {
            CaseEntity c = cases.get(RANDOM.nextInt(cases.size()));
            LocalDate hearingDate;
            if (i < 3) {
                hearingDate = today; // Today hearings
            } else if (i < 8) {
                hearingDate = today.plusDays(RANDOM.nextInt(14) + 1); // Upcoming
            } else if (i < 12) {
                hearingDate = today.minusDays(RANDOM.nextInt(30) + 1); // Past/Completed
            } else {
                hearingDate = today.minusDays(RANDOM.nextInt(60) + 1); // Cancelled
            }

            CaseEventEntity event = new CaseEventEntity();
            event.setTitle(HEARING_TYPES[RANDOM.nextInt(HEARING_TYPES.length)]);
            event.setEventType("HEARING");
            event.setDescription("Demo hearing for " + c.getCaseNumber());
            event.setDate(hearingDate);
            event.setTime(LocalTime.of(9 + RANDOM.nextInt(8), RANDOM.nextBoolean() ? 0 : 30));
            event.setCaseEntity(c);
            event.setAdvocate(advocate);
            event.setNotified(RANDOM.nextBoolean());
            CaseEventEntity saved = caseEventRepository.save(event);
            hearingIds.add(saved.getId());

            // Timeline
            try {
                timelineService.recordEvent(
                        c.getId(), c.getClient() != null ? c.getClient().getId() : null,
                        advocate.getId(), CaseTimelineService.HEARING_CREATED,
                        "Hearing Scheduled", saved.getTitle() + " on " + saved.getDate(),
                        "System (Demo)", "Hearing", saved.getId()
                );
            } catch (Exception e) {
                log.warn("Timeline record failed: {}", e.getMessage());
            }
        }

        // ── 4. Generate Documents (30) ──
        for (int i = 0; i < 30; i++) {
            CaseEntity c = cases.get(RANDOM.nextInt(cases.size()));
            Client cl = clients.get(RANDOM.nextInt(clients.size()));
            boolean isPdf = RANDOM.nextBoolean();
            byte[] content = isPdf ? SAMPLE_PDF_BYTES : SAMPLE_TXT_BYTES;
            String ext = isPdf ? ".pdf" : ".txt";
            String mime = isPdf ? "application/pdf" : "text/plain";
            String fileName = "demo_doc_" + (i + 1) + ext;

            try {
                MultipartFile mpf = new DemoSampleMultipartFile(content, fileName, fileName, mime);
                StoredFile sf = documentStorageService.store(mpf, "documents");

                Document doc = new Document();
                doc.setDocumentName(DOC_CATEGORIES[RANDOM.nextInt(DOC_CATEGORIES.length)] + " - " + fileName);
                doc.setOriginalName(fileName);
                doc.setStoredName(sf.getStoredName());
                doc.setFilePath(sf.getFilePath());
                doc.setFileSize(sf.getFileSize());
                doc.setFileType(mime);
                doc.setCategory(DOC_CATEGORIES[RANDOM.nextInt(DOC_CATEGORIES.length)]);
                doc.setDescription("Demo document for " + c.getCaseNumber());
                doc.setVersion(1);
                doc.setStatus("ACTIVE");
                doc.setAdvocate(advocate);
                doc.setCaseEntity(c);
                doc.setClient(cl);
                doc.setUploadDate(LocalDateTime.now().minusDays(RANDOM.nextInt(90)));
                Document saved = documentRepository.save(doc);
                documentIds.add(saved.getId());

                // Timeline
                try {
                    timelineService.recordEvent(
                            c.getId(), c.getClient() != null ? c.getClient().getId() : null,
                            advocate.getId(), CaseTimelineService.DOCUMENT_UPLOADED,
                            "Document Uploaded", saved.getDocumentName(),
                            "System (Demo)", "Document", saved.getId()
                    );
                } catch (Exception e) {
                    log.warn("Timeline record failed: {}", e.getMessage());
                }
            } catch (IOException e) {
                log.warn("Failed to store demo document {}: {}", fileName, e.getMessage());
            }
        }

        // ── 5. Generate Expenses (25) ──
        for (int i = 0; i < 25; i++) {
            CaseEntity c = cases.get(RANDOM.nextInt(cases.size()));
            Expense exp = new Expense();
            exp.setTitle(EXPENSE_CATEGORIES[RANDOM.nextInt(EXPENSE_CATEGORIES.length)] + " - " + c.getCaseNumber());
            exp.setAmount(500.0 + RANDOM.nextDouble() * 49500.0);
            exp.setCategory(EXPENSE_CATEGORIES[RANDOM.nextInt(EXPENSE_CATEGORIES.length)]);
            exp.setDescription("Demo expense for " + c.getCaseNumber());
            exp.setPaymentMode(PAYMENT_MODES[RANDOM.nextInt(PAYMENT_MODES.length)]);
            exp.setPaymentStatus("PAID");
            exp.setReferenceNumber("DEMO/EXP/" + (1000 + i));
            exp.setPaymentDate(new Date(System.currentTimeMillis() - (int)(RANDOM.nextDouble() * 7776000000L)));
            exp.setExpenseType("CLIENT_CASE");
            exp.setAdvocate(advocate);
            exp.setCaseEntity(c);
            exp.setClient(c.getClient());
            Expense saved = expenseRepository.save(exp);
            expenseIds.add(saved.getId());

            // Timeline
            try {
                timelineService.recordEvent(
                        c.getId(), c.getClient() != null ? c.getClient().getId() : null,
                        advocate.getId(), CaseTimelineService.EXPENSE_ADDED,
                        "Expense Added", saved.getTitle() + " - " + String.format("%.0f", saved.getAmount()),
                        "System (Demo)", "Expense", saved.getId()
                );
            } catch (Exception e) {
                log.warn("Timeline record failed: {}", e.getMessage());
            }
        }

        // Recalculate case financials after expenses
        for (Long caseId : caseIds) {
            try {
                caseFinancialService.recalculateCaseFinancials(caseId);
            } catch (Exception e) {
                log.warn("Financial recalculation failed for case {}: {}", caseId, e.getMessage());
            }
        }

        // ── 6. Generate Invoices (15) ──
        for (int i = 0; i < 15; i++) {
            CaseEntity c = cases.get(RANDOM.nextInt(cases.size()));
            double amount = 10000.0 + RANDOM.nextDouble() * 290000.0;
            String invStatus = INVOICE_STATUSES[RANDOM.nextInt(INVOICE_STATUSES.length)];
            Invoice inv = new Invoice();
            inv.setInvoiceNumber("INV-DEMO-" + (1000 + i));
            inv.setAmount(amount);
            inv.setInvoiceDate(LocalDate.now().minusDays(RANDOM.nextInt(90)));
            inv.setDueDate(inv.getInvoiceDate().plusDays(30));
            inv.setStatus(invStatus);
            inv.setCaseEntity(c);
            inv.setClient(c.getClient());
            inv.setAdvocate(advocate);
            Invoice saved = invoiceRepository.save(inv);
            invoiceIds.add(saved.getId());

            // Timeline
            try {
                timelineService.recordEvent(
                        c.getId(), c.getClient() != null ? c.getClient().getId() : null,
                        advocate.getId(), CaseTimelineService.INVOICE_GENERATED,
                        "Invoice Generated", "INV-DEMO-" + (1000 + i) + " - " + String.format("%.0f", amount),
                        "System (Demo)", "Invoice", saved.getId()
                );
            } catch (Exception e) {
                log.warn("Timeline record failed: {}", e.getMessage());
            }
        }

        // ── 7. Generate Payments (20) ──
        List<Invoice> invoices = invoiceRepository.findAllById(invoiceIds);
        for (Invoice inv : invoices) {
            if ("PAID".equals(inv.getStatus()) || RANDOM.nextDouble() < 0.3) {
                double payAmount = "PAID".equals(inv.getStatus()) ? inv.getAmount() : inv.getAmount() * (0.3 + RANDOM.nextDouble() * 0.4);
                ClientPayment pmt = new ClientPayment();
                pmt.setAmount(payAmount);
                pmt.setPaymentMode(PAYMENT_MODES[RANDOM.nextInt(PAYMENT_MODES.length)]);
                pmt.setReferenceNumber("PAY-DEMO-" + (2000 + paymentIds.size()));
                pmt.setPaymentDate(new Date(System.currentTimeMillis() - (int)(RANDOM.nextDouble() * 7776000000L)));
                pmt.setDescription("Demo payment for " + inv.getInvoiceNumber());
                pmt.setCaseEntity(inv.getCaseEntity());
                pmt.setClient(inv.getClient());
                pmt.setAdvocate(advocate);
                ClientPayment saved = clientPaymentRepository.save(pmt);
                paymentIds.add(saved.getId());

                // Timeline
                try {
                    timelineService.recordEvent(
                            inv.getCaseEntity().getId(), inv.getClient() != null ? inv.getClient().getId() : null,
                            advocate.getId(), CaseTimelineService.PAYMENT_RECEIVED,
                            "Payment Received", "Payment of " + String.format("%.0f", payAmount) + " received",
                            "System (Demo)", "Payment", saved.getId()
                    );
                } catch (Exception e) {
                    log.warn("Timeline record failed: {}", e.getMessage());
                }
            }
        }

        // Recalculate financials again after payments
        for (Long caseId : caseIds) {
            try {
                caseFinancialService.recalculateCaseFinancials(caseId);
            } catch (Exception e) {
                log.warn("Financial recalculation failed for case {}: {}", caseId, e.getMessage());
            }
        }

        // ── 8. Generate Notifications ──
        String[] notifMsgs = {
            "Demo Workspace loaded successfully",
            "New client " + clients.get(0).getName() + " registered",
            "Hearing scheduled for " + cases.get(0).getCaseNumber(),
            "Payment received for " + cases.get(1).getCaseNumber(),
            "Expense recorded for " + cases.get(2).getCaseNumber(),
            "Invoice INV-DEMO-1001 is due soon",
            "Case " + cases.get(0).getCaseNumber() + " status updated to Active"
        };
        for (String msg : notifMsgs) {
            try {
                notificationService.createNotification(msg, advocate);
            } catch (Exception e) {
                log.warn("Notification failed: {}", e.getMessage());
            }
        }

        // ── 9. Record Audit ──
        try {
            auditLogService.recordAction(
                    advocate.getId(), advocate.getFullName(),
                    "DEMO_GENERATED", AuditLogService.MODULE_SETTINGS,
                    "Demo Workspace Generated",
                    "Demo workspace with " + clientIds.size() + " clients, " + caseIds.size() + " cases generated",
                    "DemoWorkspace", null, "SUCCESS"
            );
        } catch (Exception e) {
            log.warn("Audit log failed: {}", e.getMessage());
        }

        // ── 10. Save DemoWorkspace record ──
        Map<String, List<Long>> summary = new LinkedHashMap<>();
        summary.put("clients", clientIds);
        summary.put("cases", caseIds);
        summary.put("hearings", hearingIds);
        summary.put("documents", documentIds);
        summary.put("expenses", expenseIds);
        summary.put("invoices", invoiceIds);
        summary.put("payments", paymentIds);

        DemoWorkspace dw = new DemoWorkspace();
        dw.setAdvocateId(advocate.getId());
        dw.setGeneratedAt(LocalDateTime.now());
        dw.setActive(true);
        dw.setVersion(DEMO_VERSION);
        dw.setCreatedBy(advocate.getFullName());
        try {
            dw.setRecordSummary(new ObjectMapper().writeValueAsString(summary));
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Failed to serialize record summary", e);
        }
        demoWorkspaceRepository.save(dw);

        log.info("Demo workspace generation complete for advocate: {}", advocate.getEmail());

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("status", "success");
        result.put("message", "Demo workspace generated successfully");
        result.put("recordSummary", summary);
        return result;
    }

    // ── Clear Demo Workspace ──
    @Transactional
    public Map<String, Object> clear(String email) {
        Advocate advocate = getAdvocate(email);
        DemoWorkspace dw = demoWorkspaceRepository.findByAdvocateId(advocate.getId())
                .orElseThrow(() -> new RuntimeException("No demo workspace found for this advocate."));

        Map<String, List<Long>> summary;
        try {
            summary = new ObjectMapper().readValue(dw.getRecordSummary(), LinkedHashMap.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse demo workspace record summary", e);
        }

        // Delete in dependency-safe order (child entities first)
        List<Long> hearingIds = toLongList(summary.get("hearings"));
        List<Long> expenseIds = toLongList(summary.get("expenses"));
        List<Long> paymentIds = toLongList(summary.get("payments"));
        List<Long> invoiceIds = toLongList(summary.get("invoices"));
        List<Long> documentIds = toLongList(summary.get("documents"));
        List<Long> caseIds = toLongList(summary.get("cases"));
        List<Long> clientIds = toLongList(summary.get("clients"));

        // Delete timeline events for demo cases (via caseEventRepo for events, timeline deletion is cascaded or manual)
        for (Long caseId : caseIds) {
            try {
                caseTimelineRepository.deleteByCaseId(caseId);
            } catch (Exception e) {
                log.warn("Failed to delete events for case {}: {}", caseId, e.getMessage());
            }
        }

        // Delete documents (both records and files)
        if (!documentIds.isEmpty()) {
            List<Document> docs = documentRepository.findAllById(documentIds);
            for (Document doc : docs) {
                try {
                    documentStorageService.delete(doc.getFilePath());
                } catch (Exception e) {
                    log.warn("Failed to delete document file: {}", e.getMessage());
                }
            }
            documentRepository.deleteAllById(documentIds);
        }

        // Delete in order
        if (!hearingIds.isEmpty()) caseEventRepository.deleteAllById(hearingIds);
        if (!expenseIds.isEmpty()) expenseRepository.deleteAllById(expenseIds);
        if (!paymentIds.isEmpty()) clientPaymentRepository.deleteAllById(paymentIds);
        if (!invoiceIds.isEmpty()) invoiceRepository.deleteAllById(invoiceIds);
        if (!caseIds.isEmpty()) caseRepository.deleteAllById(caseIds);
        if (!clientIds.isEmpty()) clientRepository.deleteAllById(clientIds);

        // Delete the demo workspace record
        demoWorkspaceRepository.delete(dw);

        // Audit log
        try {
            auditLogService.recordAction(
                    advocate.getId(), advocate.getFullName(),
                    "DEMO_REMOVED", AuditLogService.MODULE_SETTINGS,
                    "Demo Workspace Removed",
                    "Demo workspace with " + clientIds.size() + " clients, " + caseIds.size() + " cases removed",
                    "DemoWorkspace", null, "SUCCESS"
            );
        } catch (Exception e) {
            log.warn("Audit log failed: {}", e.getMessage());
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("status", "success");
        result.put("message", "Demo workspace removed successfully");
        return result;
    }

    // ── Helpers ──
    private Advocate getAdvocate(String email) {
        return advocateRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("Advocate not found: " + email));
    }

    private String randomName() {
        return FIRST_NAMES[RANDOM.nextInt(FIRST_NAMES.length)] + " " + LAST_NAMES[RANDOM.nextInt(LAST_NAMES.length)];
    }

    private String randomEmail(String name) {
        return name.toLowerCase().replace(" ", ".") + RANDOM.nextInt(999) + "@example.com";
    }

    private String randomCity() {
        return CITIES[RANDOM.nextInt(CITIES.length)];
    }

    private String randomCaseType() {
        return CASE_TYPES[RANDOM.nextInt(CASE_TYPES.length)];
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private List<Long> toLongList(Object obj) {
        if (obj == null) return new ArrayList<>();
        if (obj instanceof List) {
            List list = (List) obj;
            List<Long> result = new ArrayList<>();
            for (Object item : list) {
                if (item instanceof Long) {
                    result.add((Long) item);
                } else if (item instanceof Integer) {
                    result.add(((Integer) item).longValue());
                }
            }
            return result;
        }
        return new ArrayList<>();
    }

    private static byte[] createSamplePdf() {
        String pdf = "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj\nxref\n0 4\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n190\n%%EOF";
        return pdf.getBytes();
    }

    private static class DemoSampleMultipartFile implements MultipartFile {
        private final byte[] content;
        private final String name;
        private final String originalFilename;
        private final String contentType;

        DemoSampleMultipartFile(byte[] content, String name, String originalFilename, String contentType) {
            this.content = content;
            this.name = name;
            this.originalFilename = originalFilename;
            this.contentType = contentType;
        }

        @Override public String getName() { return name; }
        @Override public String getOriginalFilename() { return originalFilename; }
        @Override public String getContentType() { return contentType; }
        @Override public boolean isEmpty() { return content.length == 0; }
        @Override public long getSize() { return content.length; }
        @Override public byte[] getBytes() { return content; }
        @Override public InputStream getInputStream() { return new ByteArrayInputStream(content); }
        @Override public void transferTo(File dest) throws IOException { java.nio.file.Files.write(dest.toPath(), content); }
    }
}
