package advocate.com.advocate_app.communication.enums;

public enum NotificationType {
    HEARING_REMINDER,
    HEARING_SCHEDULED,
    HEARING_RESCHEDULED,
    CASE_CREATED,
    CASE_UPDATED,
    CASE_STATUS_UPDATED,
    CASE_CLOSED,
    PAYMENT_RECEIVED,
    PAYMENT_DUE,
    OVERDUE_PAYMENT_REMINDER,
    INVOICE_CREATED,
    INVOICE_GENERATED,
    DOCUMENT_UPLOADED,
    CLIENT_REGISTERED,
    WELCOME,
    EXPENSE_UPDATED,
    TASK_DEADLINE_REMINDER,
    PASSWORD_RESET,
    MANUAL_MESSAGE,
    CUSTOM
}
